name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: 设置 JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: 使用 Maven 构建
      run: mvn -B package --file pom.xml
    
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: ViaGeyser
        path: target/viageyser-*.jar